### ISSUE TITLE
Vulnerability in handlebars library

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#1]
Flagged by github. 

<img width="773" alt="screen shot 2018-03-16 at 10 24 42" src="https://user-images.githubusercontent.com/1169990/37515923-633bce4e-2904-11e8-983f-f95290aafa40.png">

**Comment by enginehouse** [comment]
Strange - we are not using Handlebars that I can tell....

**Comment by davelovemartin** [comment]
So `Grunticon` (grunticon-lib in particular) has a dependency on `handlebars 3.0.3`...

**Comment by Koded** [comment]
@enginehouse can we remove Grunticon?

**Comment by enginehouse** [comment]
We aren't using Grunticon - I say vaporise it : )))
