### ISSUE TITLE
Update the index page 

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#23]
Remove reference to Journeys (they are user stories).

**Comment by enginehouse** [comment]
Done

**Comment by Koded** [comment]
Just one small (almost pedantic) request... can we make the title a bit bigger?

**Comment by enginehouse** [comment]
Sure - do you mean the main H1 title?
 or the pages index little fella? @Koded

**Comment by Koded** [comment]
The little fella :)

<img width="782" alt="screen shot 2018-04-20 at 15 15 35" src="https://user-images.githubusercontent.com/1169990/39056137-c29e9e7e-44ad-11e8-87ba-912387d216b6.png">
