### ISSUE TITLE
License overview panel should link to page not jump down to the panel

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#25]
E.g. "Technical" in the "License Overview" panel on https://uksa-alpha.cxp.io/application-overview should go to: https://uksa-alpha.cxp.io/application-overview/technical

**Comment by enginehouse** [comment]
Addressed with: 206312dc83e34b3e4cfcd12c7f87ff0feedf0781

**Comment by Koded** [comment]
Passed
