### ISSUE TITLE
Notifications colour #912B88

### ISSUE THREAD

**Issue by LukeCX** [UKSpaceAgency/space-activity-licensing-alpha#29]
Notifications highlight colour should be #912B88

**Comment by enginehouse** [comment]
Fixed @LukeCX - just need to get it on stage

**Comment by Koded** [comment]
Failed testing - see #39

**Comment by Koded** [comment]
![screen shot 2018-04-24 at 10 08 20](https://user-images.githubusercontent.com/1169990/39177552-85465966-47a7-11e8-873f-824dea4dbcd2.png)

but ok on https://uksa-alpha.cxp.io/application-overview

**Comment by Koded** [comment]
Fixed
