### ISSUE TITLE
Licence colour change to pastel shades

### ISSUE THREAD

**Issue by LukeCX** [UKSpaceAgency/space-activity-licensing-alpha#30]
Please can we update the licence specific colours.

Licence name/colour - 

I-OL - #F6D1E0
LS - #F6C4AA
SP - #DCCAAE
RCS - #A4D4D0

If its a "new" licence the notification/new message needs to be the GOV.UK shade below.

LS - #F47738
I-OL - #F499BE
SP - #B58840
RCS - #28A197

**Comment by enginehouse** [comment]
I should probably get rid of the acronyms too while I am at it....

**Comment by LukeCX** [comment]
Yeah cool

In-orbit
Spaceport
Range
Launch

**Comment by Koded** [comment]
Fixed
