### ISSUE TITLE
Amend Proto Name in Nav

### ISSUE THREAD

**Issue by wotton111** [UKSpaceAgency/space-activity-licensing-alpha#35]
Amend navigation title to:

Space Activity Licence Manager

All on one line

![screen shot 2018-04-20 at 10 11 14](https://user-images.githubusercontent.com/16197634/39042648-44aa307a-4483-11e8-9ebf-ea1566f4ca34.png)

**Comment by Koded** [comment]
Still seems to be on one line.

**Comment by Koded** [comment]
Fixed
