### ISSUE TITLE
Lorem Ipsum text in a select box

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#40]
Surely this should show what the filters are?

![screen shot 2018-04-24 at 10 10 35](https://user-images.githubusercontent.com/1169990/39177700-dd50ff94-47a7-11e8-9727-b486b276021d.png)

@wotton111 - what should this be?

**Comment by wotton111** [comment]
This should just say select on landing

**Comment by Koded** [comment]
Done
