### ISSUE TITLE
Form uploads need to be native

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#42]
https://govuk-elements.herokuapp.com/form-elements/#form-file-upload

**Comment by Koded** [comment]
Failed testing: https://uksa-alpha.cxp.io/operator/technical

<img width="792" alt="screen shot 2018-04-25 at 12 06 35" src="https://user-images.githubusercontent.com/1169990/39242202-2f81910a-4881-11e8-8745-01cfbc8edaa1.png">

**Comment by Koded** [comment]
Also - if you click around "Draft" or "Ready for submission" it will launch the file upload popup.

**Comment by Koded** [comment]
Can you remove the black border and

**Comment by enginehouse** [comment]
![screen shot 2018-04-26 at 12 06 32](https://user-images.githubusercontent.com/5637994/39302368-4fffdb5c-494a-11e8-9e3b-6fa481bf14ce.png)
Do  you mean to remove the border from around it? It is native now - the border got added by default butI figured it stopped it getting lost a bit (native controls are very anonymous)
