### ISSUE TITLE
Changes to the comments

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#46]
<img width="728" alt="screen shot 2018-04-24 at 10 32 06" src="https://user-images.githubusercontent.com/1169990/39179105-59a6bcca-47ab-11e8-9b2c-6748772c40ed.png">

https://uksa-alpha.cxp.io/application-overview/frequency#notes-open

- [x] The second tab ("Private Notes") should be empty.
- [x] Capital "F" on "frequency"

**Comment by enginehouse** [comment]
In progress

**Comment by enginehouse** [comment]
Done - fixed with this 07789d9f Omitted part of the success criteria : / - capitalise ‘F’

**Comment by Koded** [comment]
Fixed
