### ISSUE TITLE
Completed application sections missing green tick icon

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#47]
![screen shot 2018-04-24 at 10 39 24](https://user-images.githubusercontent.com/1169990/39179292-da9b64ca-47ab-11e8-8783-84167f607f24.png)

https://uksa-alpha.cxp.io/operator/operator-overview-technical-submit

**Comment by enginehouse** [comment]
This is the page - there are several that look similar: 
https://uksa-alpha.cxp.io/operator/operator-overview-technical-complete

The second block down @Koded

**Comment by Koded** [comment]
Cool ta - @LukeCX wanted it on the page as well (https://uksa-alpha.cxp.io/operator/operator-overview-technical-submit).

**Comment by Koded** [comment]
Ignore me! Just talked to @LukeCX
