### ISSUE TITLE
Licence type check boxes

### ISSUE THREAD

**Issue by wotton111** [UKSpaceAgency/space-activity-licensing-alpha#50]
These should be unchecked until the licensing manager chooses the appropriate one.
![screen shot 2018-04-24 at 10 53 12](https://user-images.githubusercontent.com/16197634/39180038-c53b8770-47ad-11e8-8eee-07e1d5e1063e.png)

**Comment by enginehouse** [comment]
In progress

**Comment by Koded** [comment]
Done
