### ISSUE TITLE
Tabs not working correctly

### ISSUE THREAD

**Issue by Koded** [UKSpaceAgency/space-activity-licensing-alpha#58]
On https://uksa-alpha.cxp.io/operator/ (for example), if you click the "My Notes" link, the content does not change. However, if you click on the tab itself, i.e. the hit area around the link, the tab and content will change.

Video:

https://www.dropbox.com/s/0uqgsi2hbsthbn1/uksa-tabs.mov?dl=0

**Comment by enginehouse** [comment]
They are working correctly but the tabs (in this branch) have the same content. On this feature branch: 

https://github.com/UKSpaceAgency/space-activity-licensing-alpha/pull/56

I have refactored it to have tab-specific content - just need to merge it in @Koded

**Comment by Koded** [comment]
Fixed
